_BASE_: "basenet.yaml"
INPUT:
  FORMAT: "RGB"
DATASETS:
  TRAIN: ("MotionNet_train",)
  TEST: ("MotionNet_valid",)
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  META_ARCHITECTURE: "MotionRCNN"
  PIXEL_MEAN: [140.2013101061785, 130.66440973297173, 121.66828092729827, 3082.0454984780536]  # RGBD mean from MotionDataset_6.11 train
  PIXEL_STD: [54.83620008306015, 57.413304666067994, 63.30566038976449, 630.3761722470161] # RGBD stddev from MotionDataset_6.11 train
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NAME: "MotionROIHeads"
    NUM_CLASSES: 3
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 1.0
  ANCHOR_GENERATOR:
    SIZES: [[16, 32, 64, 128, 192]]  
SOLVER:
  CHECKPOINT_PERIOD: 6000
  IMS_PER_BATCH: 16
  STEPS: (6000, 8000)
  BASE_LR: 0.001
  MAX_ITER: 10000
VERSION: 2
