_BASE_: "motionnet.yaml"
MODEL:
  MOTIONNET:
    TYPE: PM
  POSE_ITER: 0
  MOTION_ITER: 20000
INPUT:
  DIMENSION_MEAN: [0.68188438, 0.48872801, 0.42207135]
  ROTATION_BIN_NUM: 10
  COVER_VALUE: 0.2 
  RNG_SEED: 1      
SOLVER:
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 16
  STEPS: (6000, 8000)
  BASE_LR: 0.001
  MAX_ITER: 10000
